version: "3.9"

services:
  cronmanager:
    build:
      context: .
      network: host  # Usar la red del host
    ports:
      - "8005:8000"
    volumes:
      - ./app:/app
    command: /bin/bash -c "source /venv/bin/activate && /venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app"
   

